[package]
name = "local_lru"
version = "0.2.0"
license = "MIT"
description = "A simple, thread-safe and lock-free LRU cache based on thread local storage."
edition = "2021"

[dependencies]
bytes = "1.7.2"
